### ISSUE TITLE
Could not install legacy WhatsApp

### ISSUE THREAD

**Issue by MoMemSa** [YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor#85] opened 2022-02-19 19:11 UTC
**Describe the bug**
The Legacy Whatsapp version is not installing.. Failure [-26: Package com.whatsapp new target SDK 19 doesn't support runtime permissions but the old target SDK 30 does.]

**To Reproduce**
I only run the wa_kdbe file and it gave me the below terminal output error

**Expected behavior**
The old version whatsapp should be installed

**Screenshots**
![Screenshot_5](https://user-images.githubusercontent.com/100044022/154815399-303de57e-fe5a-434f-a0fa-a6643d98587f.png)

**Terminal output or log file**
```

================================================================================
========                Current release date: 12/02/2022                ========
========                                                                ========
========  db   d8b   db  .d8b.         db   dD d8888b. d8888b. d88888b  ========
========  88   I8I   88 d8' `8b        88 ,8P' 88  `8D 88  `8D 88'      ========
========  88   I8I   88 88ooo88        88,8P   88   88 88oooY' 88ooooo  ========
========  Y8   I8I   88 88~~~88 C8888D 88`8b   88   88 88~~~b. 88~~~~~  ========
========  `8b d8'8b d8' 88   88        88 `88. 88  .8D 88   8D 88.      ========
========   `8b8' `8d8'  YP   YP        YP   YD Y8888D' Y8888P' Y88888P  ========
========                                                                ========
================================================================================

============ WhatsApp Key / Database Extrator for non-rooted Android ===========

================================================================================
===                                                                          ===
===  xxxxx  PLEASE TAKE WHATSAPP CHAT BACKUP BEFORE GETTING STARTED.  xxxxx  ===
===                                                                          ===
===     For that go to "WhatsApp settings → Chat Settings → Chat Backup"     ===
===              here take a local backup. Prepare for Worst.                ===
===                                                                          ===
===  Also if you see a folder "Android/media/com.whatsapp" copy it somewhere ===
===   safe. New versions of WhatsApp are saving data here INCLUDING IMAGES   ===
===       AND VIDEOS. I try to save it while uninstalling WhatsApp but       ===
===                        YOU CAN NEVER BE TOO SAFE.                        ===
===                                                                          ===
===     This script can extract your WhatsApp msgstore.db (non crypt12,      ===
===   un-encrypted file) and your "key" file from "/data/data/com.whatsapp"  ===
===  directory in Android 4.0+ device without root access. However you need  ===
===   to have JAVA installed on your system in order to "view the extract".  ===
===  If you don't have JAVA installed then you can "view extract" later by   ===
===   running "view_extract.py". The idea is to install a "Legacy WhatsApp"  ===
===       temporarily on your device in order to get the android backup      ===
===    permission. You should not lose any data and your current WhatsApp    ===
===   version will be installed after this process so don't panic and don't  ===
=== stop this script while it's working. However if something fails you can  ===
===    run "restore_whatsapp.py" and reinstall current WhatsApp or simply    ===
===                    update that from Google Play Store.                   ===
===                                                                          ===
===                      Script by: Yuvraj Raghuvanshi                       ===
===                      Github.com/YuvrajRaghuvanshiS                       ===
================================================================================

[Saturday 19/02/2022, 23:06:38] Found Java v1.8.0_321 installed on system. Continuing...

[Saturday 19/02/2022, 23:06:38] Turned off wifi and mobile data...
[Saturday 19/02/2022, 23:06:38] Please read above instructions carefully ↑ . Continue? (default y): y


[Saturday 19/02/2022, 23:06:38] If you haven't already, it is adviced to take a WhatsApp chat backup by going to "WhatsApp settings → Chat Settings → Chat Backup". Hit "Enter" key to continue.
[Saturday 19/02/2022, 23:06:38] Connected to SM-A515F
[Saturday 19/02/2022, 23:06:38] WhatsApp V2.22.4.74 installed on device
[Saturday 19/02/2022, 23:06:38] Found legacy WhatsApp V2.11.431 apk in "helpers/" folder
[Saturday 19/02/2022, 23:06:38] Backing up WhatsApp 2.22.4.74 apk, the one installed on device to "/data/local/tmp/WhatsAppbackup.apk" in your phone.
[Saturday 19/02/2022, 23:06:38] Apk backup is completed.
[Saturday 19/02/2022, 23:06:38] Uninstalling WhatsApp, skipping data.
[Saturday 19/02/2022, 23:06:38] Uninstalled.
[Saturday 19/02/2022, 23:06:38] Installing legacy WhatsApp V2.11.431, hold tight now.
[Saturday 19/02/2022, 23:06:38] Could not install legacy WhatsApp
[Saturday 19/02/2022, 23:06:38] adb: failed to install helpers/LegacyWhatsApp.apk: Failure [-26: Package com.whatsapp new target SDK 19 doesn't support runtime permissions but the old target SDK 30 does.]
Performing Streamed Install
[Saturday 19/02/2022, 23:06:38] Trying to restore WhatsApp in 00:01.
[Saturday 19/02/2022, 23:06:38] Reinstalling original WhatsApp.
[Saturday 19/02/2022, 23:06:38] Reinstallation complete.


[Saturday 19/02/2022, 23:06:38] Exiting...
[Saturday 19/02/2022, 23:06:38] Turn off USB debugging [and USB debugging (Security Settings)] if you're done.
[Saturday 19/02/2022, 23:06:38] Hit "Enter" key to continue....
```

**Additional context**

**Comment by YuvrajRaghuvanshiS** [comment] 2022-02-21 07:22
Duplicate of #19 
Run script with reboot flag. `python3 wa_kdbe.py --allow-reboot`.

**Closed by YuvrajRaghuvanshiS** 2022-02-21 07:22 UTC
