### ISSUE TITLE
Display message upon failure to download legacy APK

### ISSUE THREAD

**Issue by ReallyCoolName** [YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor#68] opened 2021-06-12 17:19 UTC
currently there is no indication when the legacy APK is not downloaded. It simply exits.

this is the same problem as in #65 but on windows.

**Comment by YuvrajRaghuvanshiS** [comment] 2021-06-29 07:51
duplicate of #65

**Closed by YuvrajRaghuvanshiS** 2021-06-29 07:51 UTC
Labels: duplicate
