### ISSUE TITLE
The command "python3 wa_kdbe.py" returns error

### ISSUE THREAD

**Issue by NioBee** [YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor#57] opened 2021-04-18 16:06 UTC
**Describe the bug**
When I follow the instructions provided in the home of this release I receive an error message inserting the command you suggest into GIT CMD 

**To Reproduce**
1. run 'GIT CMD' as admin
2. Enter 'python3 wa_kdbe.py'
3. See error ' _"python3" non è riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch._'

**solution**
instead of 'python3 wa_kdbe.py' use **'py wa_kdbe.py'**
Changing this line worked good for me, the procedure was then completed without further errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/41695549/115152170-4f2c0b80-a070-11eb-9e06-cb342ce2f2a6.png)

**Desktop:**
 - OS: Windows 10 x64
 - Python 3.9 64 bit
 - Git for Windows v2.19.1
 - Python is allready defined in PATH

**Comment by YuvrajRaghuvanshiS** [comment] 2021-04-18 16:11
In first run it only installs dependencies sometimes. Try running again

**Comment by YuvrajRaghuvanshiS** [comment] 2021-04-18 16:12
That `py` thing. I think that is only for your system somehow.

**Comment by YuvrajRaghuvanshiS** [comment] 2021-04-18 16:16
Keeping this open until I figure out what caused that.Also if not specifically requested you should never run programs as admin.

**Comment by NioBee** [comment] 2021-04-18 16:44
> Also if not specifically requested you should never run programs as admin.

thanks

**Comment by NioBee** [comment] 2021-04-18 16:47
> That `py` thing. I think that is only for your system somehow.

As I first run into that problem I googled it and found the solution [here](https://it.coredump.biz/questions/39910730/python3-is-not-recognized-as-an-internal-or-external-command-operable-program-or-batch-file) I think it's somehow a issue that occurs in windows systems

**Comment by YuvrajRaghuvanshiS** [comment] 2021-04-18 17:00
I will look into that. Thanks for the link

**Comment by YuvrajRaghuvanshiS** [comment] 2021-04-19 03:51
As I've read on many forums it looks like this is the new of way of running python files but I don't know in which version of python it is implemented or how many people this new method will going to cover. I will add a troubleshoot point about this issue for now until I read about it more.

**Comment by YuvrajRaghuvanshiS** [comment] 2021-04-19 03:58
Also can you check if double clicking the file runs it?

**Comment by NioBee** [comment] 2021-04-19 08:02
> Also can you check if double clicking the file runs it?

Ok so, if I double click it without a connected phone the window opens and immediately closes itself without the time to read what it says.. Perhaps it could be useful to add something like an error message: please connect your phone..
here a short gif showing what happens:
![try_to_run](https://user-images.githubusercontent.com/41695549/115201842-0cad1200-a0f6-11eb-8834-cc910205d9a4.gif)

If I click it having my phone connected it seems to work right:
![try_to_run2](https://user-images.githubusercontent.com/41695549/115201910-1b93c480-a0f6-11eb-81a9-dcc1064e78c2.gif)

One small issue, at this point if I select N (for no) the process advances anyway.. 
![image](https://user-images.githubusercontent.com/41695549/115202073-4a119f80-a0f6-11eb-863f-54b10f41cc56.png)

**Comment by YuvrajRaghuvanshiS** [comment] 2021-04-19 09:29
> if I double click it without a connected phone the window opens and immediately closes itself without the time to read what it says

That is happening because I never really thought of running it by double clicking. To stop console from closing on exit I need to use
```python 
import os
os.system('pause')
```
before quitting. I added that in recent commit on master for almost every exit and exception case in my code. Hopefully I did not break anything I was in hurry while doing that.

> One small issue, at this point if I select N (for no) the process advances anyway..

My bad I added that second line (yellow backup advice) recently and did not pay attention that I was checking for input after printing both. I fixed it too.

You can test these changes if you like. Be sure to pull latest changes
```bash
git checkout master
git pull origin
```

**Comment by NioBee** [comment] 2021-04-19 09:51
Super, now it works as expected.
BTW really nice work!! It helped me saving messages from a damaged phone!!! ❤️

Without phone:
![newrun](https://user-images.githubusercontent.com/41695549/115217033-5ea96400-a105-11eb-9dae-6b2aebbb907a.gif)

With phone:
![newrun2](https://user-images.githubusercontent.com/41695549/115217061-65d07200-a105-11eb-8586-1a8151bb398a.gif)

**Comment by YuvrajRaghuvanshiS** [comment] 2021-04-19 10:42
> Super, now it works as expected. 

Cool.

>  BTW really nice work!! It helped me saving messages from a damaged phone!!! ❤️

That's amazing. Glad to hear that.
Closing this issue.

**Closed by YuvrajRaghuvanshiS** 2021-04-19 10:42 UTC

**Comment by Tango2607** [comment] 2022-01-04 12:41
Hi Yuvraj, thanks for your script, you are geniuos!
after starting the script:
C:\...\...\...\WhatsApp-Key-Database-Extractor-master>wa_kdbe.py
I receive  : 
The command "pip3" is either misspelled or
could not be found.

**Comment by YuvrajRaghuvanshiS** [comment] 2022-01-04 12:56
Hi, thanks.

This is auto dependencies installer code. Check if pip is installed on your system. Install pip if not already installed and then install requirements manually using either of the commands below:

pip install -r requirements.txt
pip3 install -r requirements.txt
python3 -m pip install -r requirements.txt
python -m install -r requirements.txt

PS: Run these command in the folder as wa_kdbe.py.

Stay healthy,

Yuvraj Raghuvanshi.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by bogdank0** [comment] 2023-08-22 17:46
@YuvrajRaghuvanshiS  Any ideas what the problem is and how to solve it? Already reinstalled the repository. I tried to connect through "TCP/USB". Does not work. I need to do --tar-only. If you open a Python file directly in the folder, it does not find the keys, but extracts 4 files.

Therefore, I want to get all the files through cmd. Is it possible to add --tar-only somehow? 
![image](https://github.com/YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor/assets/119637525/18e4a92d-d54f-464a-8cb4-a36ecd4964d1)

used to give an error, but I googled and they told me that I need to download and throw that file into two folders. I did and got the error as described above
![photo_2023-08-22_18-39-24](https://github.com/YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor/assets/119637525/f6ea7c39-a52b-4187-95d7-d3689cbf5f6f)
